/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zacheryirvin;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class App {

    public static void main(String[] args) {
      Set<SpaceBody> solarSystem = new HashSet<>();
      Set<SpaceBody> bodys = new HashSet<>();
      SpaceBody earth = new SpaceBody("Earth", "planet");
      SpaceBody earthTwo = new SpaceBody("Earth", "star");
      SpaceBody moon = new SpaceBody("Moon", "moon");
      SpaceBody moonTwo = new SpaceBody("MoonTwo", "moon");
      solarSystem.add(earth);
      solarSystem.add(earthTwo);
      bodys.add(earth);
      bodys.add(earthTwo);
      bodys.add(moon);
      bodys.add(moonTwo);
      earth.addSatellite(moon);
      earth.addSatellite(moonTwo);

      for(SpaceBody b : solarSystem) {
        System.out.println(b);
      }

      for(SpaceBody bod : bodys) {
        System.out.println(bod);
      }

      earth.getSatellites();
    }
}
