/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zacheryirvin;

public class App {
    private static StockList stockList = new StockList();

    public static int sellItem(Basket basket, String item, int quantity) {
      StockItem stockItem = stockList.get(item);
      if(stockItem == null) {
        System.out.println("We don't sell " + item);
        return 0;
      }

      if(stockList.sellStock(item, quantity) != 0) {
        basket.addToBasket(stockItem, quantity);
        return quantity;
      }
      return 0;
    }
    public static void main(String[] args) {
      StockItem temp = new StockItem("bread", 0.86, 100);
      stockList.addStock(temp);
      temp = new StockItem("cake", 1.18, 7);
      stockList.addStock(temp);
      temp = new StockItem("car", 12.50, 2);
      stockList.addStock(temp);
      temp = new StockItem("chair", 62.00, 10);
      stockList.addStock(temp);
      temp = new StockItem("cup", 0.50, 200);
      stockList.addStock(temp);
      temp = new StockItem("door", 72.95, 4);
      stockList.addStock(temp);
      temp = new StockItem("juice", 2.50, 36);
      stockList.addStock(temp);
      temp = new StockItem("phone", 96.99, 35);
      stockList.addStock(temp);
      temp = new StockItem("towel", 2.48, 88);
      stockList.addStock(temp);
      temp = new StockItem("vase", 8.76, 40);
      stockList.addStock(temp);
      temp = new StockItem("vase", 8.76, 10);
      stockList.addStock(temp);

      Basket zbasket = new Basket("Zach");
      sellItem(zbasket, "cake", 5);
      sellItem(zbasket, "car", 2);
      sellItem(zbasket, "spinner", 4);
      sellItem(zbasket, "vase", 25);

      System.out.println(" ");
      System.out.println(zbasket);

      System.out.println(stockList);

    }
}
